---

- hosts: ec2-hosts
  remote_user: ec2-user
  become: yes
  tasks:
    
  - name: add nginx-repo
    yum: name=http://nginx.org/packages/rhel/7/noarch/RPMS/nginx-release-rhel-7-0.el7.ngx.noarch.rpm
    
  - name: install nginx
    yum: name=nginx state=latest
    
  - name: install git
    yum: name=git state=latest
    
  - name: get index_html
    git: repo=https://github.com/puppetlabs/exercise-webpage.git dest=/tmp/tmp
    
  - name: change nginx port to 8000
    replace: dest=/etc/nginx/conf.d/default.conf backup=yes regexp='\s80;' replace='8000;'
 
  - name: copy file
    copy: remote_src=true src=/tmp/tmp/index.html dest=/usr/share/nginx/html
    
  - name: set selinux to permissive
    command: 'setenforce 0'
    
  - name: start service nginx
    service: name=nginx state=started