#playbook to launch instances on aws
- hosts: localhost
  connection: local
  gather_facts: False

  tasks:
    - name: make one instance
      ec2: image=ami-b6bdde86
           instance_type=t1.micro
           region=us-west-2
           wait=true
      register: ec2info
     
    #- debug: var=ec2_info
    #- debug: var=ec2_info.instances.public_dns_name
    
    - add_host: hostname={{ item.public_dns_name }} groupname=ec2hosts
      with_items: ec2info.instances