#playbook to launch instances on aws
- hosts: localhost
  connection: local
  gather_facts: False

  tasks:
    - name: make one instance
      ec2: image=ami-b6bdde86
           instance_type=t1.micro
           region=us-west-2
           wait=true
      register: ec2_info
     
    - debug: var=ec2_info
    - debug: var=item
        with_items:ec2_info.instance_ids
    - debug: msg="Assigned public DNS name is {{ item.dns_name }}"
        with_items:ec2_info.instances
    